apiVersion: apps/v1
kind: Deployment
metadata:
  name: "terraform-example"
  labels:
    test: "MyReactApp"
  annotations:
    ad.datadoghq.com/web.logs: '[{"source": "web","service": "web","tags": ["env:prod"]}]'
spec:
  replicas: 3
  selector:
    matchLabels:
      test: "MyReactApp"
  template:
    metadata:
      labels:
        test: "MyReactApp"
    spec:
      serviceAccountName: "my-react-app"
      containers:
        - name: my-react-app-deployment
          image: "892893225782.dkr.ecr.us-west-2.amazonaws.com/my-react-app:{{ .Values.commit }}"
          resources:
            limits:
              memory: "1Gi"
              cpu: "320m"
            requests:
              memory: "0.5Gi"
              cpu: "300m"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP

