# build environment
FROM node:19.5.0-alpine as build
ARG ENVIRONMENT
ENV ENVIRONMENT=$ENVIRONMENT
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json ./
COPY package-lock.json ./
RUN npm ci --silent
RUN npm install react-scripts@3.4.1 -g --silent
COPY . ./