version: '3.7'

services:

  sample:
    container_name: sample
    build:
      context: .
      dockerfile: Dockerfile_dev
      args:
        - ENVIRONMENT=development
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    command: npm start
    environment:
      - CHOKIDAR_USEPOLLING=true