version: '3.7'

services:

  sample:
    container_name: sample
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # This argument is used in build time in Dockerfile to define that
        # how we want to create the image from Dockerfile.
        # It should be development for dev purposes and production for production purposes.
        - ENVIRONMENT=production
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
      - 80:80
    environment:
      - CHOKIDAR_USEPOLLING=true